on:
  pull_request:
    branches: [main]
    paths:
      - 'readme.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: niiiice-lint
        run: ./.github/workflows/repo_linter.sh
